<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUnDJNKP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUnDJNKP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUnDJNKP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUnDJNKP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUnDJNKP\App_KernelDevDebugContainer([
    'container.build_hash' => 'UnDJNKP',
    'container.build_id' => '2d29f61b',
    'container.build_time' => 1775588197,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUnDJNKP');
