<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_home' => [[], ['_controller' => 'App\\Controller\\StoreController::index'], [], [['text', '/']], [], [], []],
    'app_products' => [[], ['_controller' => 'App\\Controller\\StoreController::products'], [], [['text', '/products']], [], [], []],
    'app_product_details' => [['id'], ['_controller' => 'App\\Controller\\StoreController::productDetails'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/products']], [], [], []],
    'app_categories' => [[], ['_controller' => 'App\\Controller\\StoreController::categories'], [], [['text', '/categories']], [], [], []],
    'app_products_by_category' => [['slug'], ['_controller' => 'App\\Controller\\StoreController::productsByCategory'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/categories']], [], [], []],
    'app_cart' => [[], ['_controller' => 'App\\Controller\\StoreController::cart'], [], [['text', '/cart']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\StoreController::login'], [], [['text', '/login']], [], [], []],
    'app_profile' => [[], ['_controller' => 'App\\Controller\\StoreController::profile'], [], [['text', '/profile']], [], [], []],
    'App\Controller\StoreController::index' => [[], ['_controller' => 'App\\Controller\\StoreController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\StoreController::products' => [[], ['_controller' => 'App\\Controller\\StoreController::products'], [], [['text', '/products']], [], [], []],
    'App\Controller\StoreController::productDetails' => [['id'], ['_controller' => 'App\\Controller\\StoreController::productDetails'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/products']], [], [], []],
    'App\Controller\StoreController::categories' => [[], ['_controller' => 'App\\Controller\\StoreController::categories'], [], [['text', '/categories']], [], [], []],
    'App\Controller\StoreController::productsByCategory' => [['slug'], ['_controller' => 'App\\Controller\\StoreController::productsByCategory'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/categories']], [], [], []],
    'App\Controller\StoreController::cart' => [[], ['_controller' => 'App\\Controller\\StoreController::cart'], [], [['text', '/cart']], [], [], []],
    'App\Controller\StoreController::login' => [[], ['_controller' => 'App\\Controller\\StoreController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\StoreController::profile' => [[], ['_controller' => 'App\\Controller\\StoreController::profile'], [], [['text', '/profile']], [], [], []],
];
